[package]
name = "psl_engine_v2_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "psl_engine_v2_core"
path = "src/lib.rs"

[[bin]]
name = "engine"
path = "src/bin/match_engine.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
codegen-units = 1
lto = "thin"
