"""Legacy Const class - delegates to psl_core for all game constants."""

from psl_core.constants import (
    FORWARD, MIDFIELD, GUARD, GOALKEEPER,
    STARS, COLOR, STATUS, ABILITIES, GK_ABILITIES,
    STYLE, GK_STYLE, FORMATION, REAL_ABILITY,
    NPC_STYLE, NPC, DIFFICULTY, ITEM, TIMES_EVERYDAY,
    POSITION_MAP,
)


class Const:
    FORWARD = FORWARD
    MIDFIELD = MIDFIELD
    GUARD = GUARD
    GOALKEEPER = GOALKEEPER
    POSITIONS = ["前锋", "中场", "后卫", "门将"]
    STARS = STARS
    COLOR = COLOR
    STATUS = STATUS
    ABILITIES = ABILITIES
    GK_ABILITIES = GK_ABILITIES
    STYLE = STYLE
    GK_STYLE = GK_STYLE
    FORMATION = FORMATION
    REAL_ABILITY = REAL_ABILITY
    NPC_STYLE = NPC_STYLE
    NPC = NPC
    DIFFICULTY = DIFFICULTY
    ITEM = ITEM
    TIMES_EVERYDAY = TIMES_EVERYDAY
